### ISSUE TITLE
v1.x roadmap

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/ts-regex-builder#57]
## Regex features

- [ ] interoperability with RegExp literals
- [ ] negated character class escapes (`\W`, `\D`, `\S`)
- [ ] lazy regex quantifiers
- [ ] named captures
- [ ] word boundary anchor (`\b`)
- [ ] backreferences
- [ ] named backreferences
- [ ] lookahead assertions
- [ ] lookbehind assertions
- [ ] unicode character class escapes (`\u`, `\U`)
- [ ] regex flag: dotAll
- [ ] regex flag: unicode
- [ ] regex flag: unicodeSets
- [ ] regex flag: sticky

## Babel features

- [ ] Static DSL compilation (!)

## Infrastructure

- [ ] Documentation website (Docusaurus, Vocs, etc)
- [ ] Code Coverage stats
